# Generated by Django 6.1 on 2026-08-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=50, unique=True, verbose_name='รหัสสินค้า (SKU)')),
                ('name', models.CharField(max_length=150, verbose_name='ชื่ออะไหล่')),
                ('category', models.CharField(choices=[('SW', 'สวิตช์/เบรกเกอร์ (Switch/Breaker)'), ('CBL', 'สายไฟ/อุปกรณ์เชื่อมต่อ (Cable/Connector)'), ('IC', 'ไอซี/แผงวงจร (IC/Board)'), ('SEN', 'เซ็นเซอร์ (Sensor)'), ('RLY', 'รีเลย์ (Relay)'), ('OTH', 'อื่นๆ (Others)')], max_length=3, verbose_name='หมวดหมู่')),
                ('quantity', models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ (ชิ้น)')),
                ('import_date', models.DateField(verbose_name='วันที่นำเข้าล่าสุด')),
                ('specifications', models.TextField(blank=True, verbose_name='สเปกและรายละเอียดทางเทคนิค')),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/', verbose_name='รูปภาพอะไหล่')),
            ],
        ),
    ]
