# Generated by Django 6.1 on 2026-08-17 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='category',
            field=models.CharField(choices=[('IC', 'ไอซี/แผงวงจร (IC/Board)'), ('SENSOR', 'เซ็นเซอร์ (Sensor)'), ('SWITCH', 'สวิตช์/เบรกเกอร์ (Switch/Breaker)'), ('RELAY', 'รีเลย์ (Relay)'), ('CABLE', 'สายไฟ/อุปกรณ์เชื่อมต่อ (Cable/Connector)'), ('OTHER', 'อื่นๆ (Others)')], max_length=20, verbose_name='หมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่ออะไหล่'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวนคงเหลือ (ชิ้น)'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('IN', 'นำเข้า (Stock In)'), ('OUT', 'เบิกออก (Stock Out)')], max_length=3, verbose_name='ประเภทรายการ')),
                ('quantity', models.PositiveIntegerField(verbose_name='จำนวน')),
                ('action_by', models.CharField(max_length=100, verbose_name='ผู้ทำรายการ/ผู้เบิก')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วัน-เวลาที่ทำรายการ')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_app.sparepart', verbose_name='อะไหล่')),
            ],
        ),
    ]
