# Generated by Django 6.1 on 2026-09-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_app', '0002_alter_sparepart_category_alter_sparepart_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่งจัดเก็บ (เช่น ตู้ A ชั้น 2)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ (เช่น ซ่อมพัดลมให้ลูกค้า)'),
        ),
    ]
