# Generated by Django 6.1 on 2026-09-06 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('role', models.CharField(choices=[('admin', 'ผู้ดูแลระบบ (Admin)'), ('member', 'ช่างซ่อม/พนักงาน (Member)'), ('guest', 'ผู้เยี่ยมชม (Guest)')], default='guest', max_length=10, verbose_name='บทบาท')),
                ('status', models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ไม่อนุมัติ'), ('suspended', 'ระงับการใช้งาน')], default='pending', max_length=15, verbose_name='สถานะบัญชี')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='เหตุผล/หมายเหตุจากแอดมิน')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุดเมื่อ')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_made', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ดำเนินการล่าสุด')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
